using Azure.Core;
using Microsoft.AspNetCore.Mvc;
using QRCoder;
using System;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using VibeWave.DataAccess.Repository;
using VibeWave.DataAccess.Repository.IRepository;
using VibeWave.Models;
using static QRCoder.PayloadGenerator;

namespace VibeWave.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class BookingController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public BookingController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            var bookings = _unitOfWork.Booking
             .GetAll(includeProperties: "Concert")
             .ToList();

            return View(bookings);
        }

            // Create
            public IActionResult Create(int id)
        {
            Concert? concert = _unitOfWork.Concert.Get(u => u.Id == id);
            if (concert == null)
            {
                return NotFound();
            }
            return View(concert);
        }

        // POST Create
        [HttpPost]
        //public IActionResult Create(Booking booking)
        //{
        //    var concert = _unitOfWork.Concert.Get(u => u.Id == booking.ConcertId);

        //    if (concert == null)
        //    {
        //        return NotFound();
        //    }

        //    if (!ModelState.IsValid)
        //    {
        //        return View(concert);
        //    }

        //    booking.TotalPrice = concert.TicketPrice * booking.NumberOfTickets;
        //    booking.BookingDate = DateTime.Now;

        //    string url = Url.Action("BookingDetails", "Booking", new { id = booking.Id, area = "Customer" }, Request.Scheme);
        //    string qrCodeImage = GenerateQrCode(url);


        //    _unitOfWork.Booking.Add(booking);
        //    _unitOfWork.Save();



        //    booking.QrCodeUrl = qrCodeImage; // Generated by ChatGpt

        //    _unitOfWork.Save();

        //    return RedirectToAction("BookingDetails", "Booking", new { id = booking.Id, area = "Customer" });
        //}

        public IActionResult Create(int ConcertId, string CustomerName, string Email, int NumberOfTickets)
        {
            try
            {
                var concert = _unitOfWork.Concert.Get(u => u.Id == ConcertId);
                if (concert == null) return NotFound();

                var booking = new Booking
                {
                    ConcertId = ConcertId,
                    CustomerName = CustomerName,
                    Email = Email,
                    NumberOfTickets = NumberOfTickets,
                    TotalPrice = concert.TicketPrice * NumberOfTickets,
                    BookingDate = DateTime.Now,
                    QrCodeUrl = null
                };

                _unitOfWork.Booking.Add(booking);
                _unitOfWork.Save();

                string url = Url.Action("BookingDetails", "Booking",
                    new { id = booking.Id, area = "Customer" }, Request.Scheme);

                string qrCodeImage = GenerateQrCode(url);

                // Update booking with QR code
                booking.QrCodeUrl = qrCodeImage;
                _unitOfWork.Save();

                return RedirectToAction("BookingDetails", "Booking",
                    new { id = booking.Id, area = "Customer" });
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"ERROR: {ex.ToString()}");
                TempData["Error"] = "Failed to create booking: " + ex.Message;
                return RedirectToAction("Index", "Home", new { area = "Customer" });
            }
        }

        public IActionResult BookingDetails(int id)
        {
            var booking = _unitOfWork.Booking.Get(
                u => u.Id == id,
                includeProperties: "Concert"
            );

            if (booking == null)
            {
                return NotFound();
            }

            return View(booking);
        }

        private string GenerateQrCode(string text)
        {
            using (QRCodeGenerator qrGenerator = new QRCodeGenerator())
            {
                QRCodeData qrCodeData = qrGenerator.CreateQrCode(text, QRCodeGenerator.ECCLevel.Q);
                QRCode qrCode = new QRCode(qrCodeData);

                using (Bitmap qrImage = qrCode.GetGraphic(20))
                {
                    using (MemoryStream ms = new MemoryStream())
                    {
                        qrImage.Save(ms, ImageFormat.Png);
                        byte[] byteImage = ms.ToArray();
                        return "data:image/png;base64," + Convert.ToBase64String(byteImage);
                    }
                }
            }
        }

        public IActionResult Confirmation()
        {
            return View();
        }

        //Delete
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Booking? bookingFromDb = _unitOfWork.Booking.Get(u => u.Id == id);
            if (bookingFromDb == null)
            {
                return NotFound();
            }
            return View(bookingFromDb);
        }

        //Delete
        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePOST(int? id)
        {
            Booking? obj = _unitOfWork.Booking.Get(u => u.Id == id);
            if (obj == null)
            {
                return NotFound();
            }
            _unitOfWork.Booking.Remove(obj);
            _unitOfWork.Save();
            TempData["success"] = " Booking Details Deleted Successfully";
            return RedirectToAction("Index");
        }
    }
}