// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VibeWave.Data;

#nullable disable

namespace VibeWave.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260409212942_SeedConcertTable")]
    partial class SeedConcertTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VibeWave.Models.Concert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ConcertCategory")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ConcertName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("DisplayDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("DisplayTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("Concert");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActorName = "ABC",
                            ConcertCategory = "More Music",
                            ConcertName = "Come Together - Born to Run - Bruce Springsteen",
                            DisplayDate = new DateOnly(2026, 5, 1),
                            DisplayTime = new TimeOnly(0, 20, 0)
                        },
                        new
                        {
                            Id = 2,
                            ActorName = "ABC",
                            ConcertCategory = "Comedy",
                            ConcertName = "Kyla Cobbler - Not My Lemons",
                            DisplayDate = new DateOnly(2026, 5, 1),
                            DisplayTime = new TimeOnly(0, 20, 0)
                        },
                        new
                        {
                            Id = 3,
                            ActorName = "ABC",
                            ConcertCategory = "Rock and Pop",
                            ConcertName = "Nurse Georgie Carroll - Infectious",
                            DisplayDate = new DateOnly(2026, 5, 1),
                            DisplayTime = new TimeOnly(0, 20, 0)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
